# Generated by Django 5.2.8 on 2025-11-18 08:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Equipment name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Name must be at least 2 characters long')])),
                ('model', models.CharField(help_text='Equipment model', max_length=100)),
                ('serial_number', models.CharField(help_text='Equipment serial number', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number must be 3-50 characters (letters, numbers, hyphens)', regex='^[A-Z0-9\\-]{3,50}$')])),
                ('manufacturer', models.CharField(help_text='Equipment manufacturer', max_length=100)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Under Maintenance'), ('CALIBRATION', 'Needs Calibration'), ('OUT_OF_SERVICE', 'Out of Service')], default='OPERATIONAL', help_text='Current equipment status', max_length=20)),
                ('calibration_due_date', models.DateField(help_text='Next calibration due date')),
                ('calibration_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Calibration frequency', max_length=20)),
                ('last_calibration_date', models.DateField(blank=True, help_text='Date of last calibration', null=True)),
                ('last_maintenance_date', models.DateField(blank=True, help_text='Date of last maintenance', null=True)),
                ('next_maintenance_date', models.DateField(blank=True, help_text='Next maintenance due date', null=True)),
                ('location', models.CharField(help_text='Equipment location in lab', max_length=100)),
                ('is_critical_equipment', models.BooleanField(default=False, help_text='Whether this is critical equipment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Additional equipment notes', null=True)),
            ],
            options={
                'verbose_name': 'Lab Equipment',
                'verbose_name_plural': 'Lab Equipment',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='labtechnici_name_733d41_idx'), models.Index(fields=['serial_number'], name='labtechnici_serial__2b1299_idx'), models.Index(fields=['status'], name='labtechnici_status_3614b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.FileField(blank=True, help_text='Upload test result file (PDF, Image, Document)', null=True, upload_to='lab_reports/')),
                ('results', models.TextField(blank=True, help_text='Detailed test results and findings', null=True, validators=[django.core.validators.MinLengthValidator(10, message='Results must be at least 10 characters long')])),
                ('comments', models.TextField(blank=True, help_text='Technician comments and observations', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current report status', max_length=20)),
                ('result_status', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('CRITICAL', 'Critical'), ('INCONCLUSIVE', 'Inconclusive')], help_text='Overall result status', max_length=20, null=True)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT (Immediate)')], default='ROUTINE', help_text='Report priority level', max_length=10)),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when test was performed')),
                ('completed_date', models.DateTimeField(blank=True, help_text='Date and time when report was completed', null=True)),
                ('verification_date', models.DateTimeField(blank=True, help_text='Date and time when report was verified', null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Verification notes from doctor', null=True)),
                ('normal_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum normal range value', max_digits=10, null=True)),
                ('normal_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum normal range value', max_digits=10, null=True)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=2, help_text='Measured test value', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, help_text='Measurement unit (e.g., mg/dL, mmol/L)', max_length=20, null=True)),
                ('is_quality_controlled', models.BooleanField(default=False, help_text='Whether quality control was performed')),
                ('quality_control_notes', models.TextField(blank=True, help_text='Quality control notes and observations', null=True)),
                ('instrument_used', models.CharField(blank=True, help_text='Instrument used for testing', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_critical_result', models.BooleanField(default=False, help_text='Whether this is a critical result that requires immediate attention')),
                ('critical_result_acknowledged', models.BooleanField(default=False, help_text='Whether critical result was acknowledged by doctor')),
                ('critical_result_acknowledged_date', models.DateTimeField(blank=True, help_text='Date and time when critical result was acknowledged', null=True)),
                ('critical_result_acknowledged_by', models.ForeignKey(blank=True, help_text='Doctor who acknowledged critical result', limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_critical_results', to='adminapp.staff')),
                ('lab_request', models.OneToOneField(help_text='Select lab request for this report', on_delete=django.db.models.deletion.CASCADE, related_name='lab_report', to='doctor.labrequest')),
                ('technician', models.ForeignKey(help_text='Lab technician performing the test', limit_choices_to={'role': 'LABTECH'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Doctor who verified the report', limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to='adminapp.staff')),
            ],
            options={
                'verbose_name': 'Lab Report',
                'verbose_name_plural': 'Lab Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lab_request'], name='labtechnici_lab_req_b50f9b_idx'), models.Index(fields=['technician'], name='labtechnici_technic_245818_idx'), models.Index(fields=['status'], name='labtechnici_status_085328_idx'), models.Index(fields=['test_date'], name='labtechnici_test_da_9eb2b9_idx'), models.Index(fields=['result_status'], name='labtechnici_result__26c676_idx')],
            },
        ),
    ]
