# Generated by Django 5.2.8 on 2025-11-18 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('doctor', '0001_initial'),
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, help_text='Auto-generated bill number', max_length=20, unique=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=300.0, help_text='Consultation fee', max_digits=10)),
                ('medicine_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total medicine cost', max_digits=10)),
                ('lab_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total laboratory test costs', max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Other miscellaneous charges', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final total amount after calculations', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid by patient', max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining balance to be paid', max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], help_text='Payment method used', max_length=20, null=True)),
                ('billing_date', models.DateField(default=django.utils.timezone.now, help_text='Date when bill was created')),
                ('due_date', models.DateField(blank=True, help_text='Due date for payment', null=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date when payment was made', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created the bill', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.staff')),
                ('lab_requests', models.ManyToManyField(blank=True, help_text='Related lab tests', related_name='bills', to='doctor.labrequest')),
                ('patient', models.ForeignKey(help_text='Select patient for billing', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='receptionist.patient')),
                ('prescription', models.ForeignKey(blank=True, help_text='Related prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='doctor.prescription')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billing Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bill_number'], name='billing_bil_bill_nu_85304b_idx'), models.Index(fields=['patient', 'billing_date'], name='billing_bil_patient_ec3bc4_idx'), models.Index(fields=['payment_status'], name='billing_bil_payment_061d84_idx')],
            },
        ),
    ]
