# Generated by Django 5.2.8 on 2025-11-18 08:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='Medicine name', max_length=100, validators=[django.core.validators.RegexValidator(message='Medicine name can only contain letters, numbers, spaces, hyphens, dots and parentheses', regex='^[a-zA-Z0-9\\s\\-\\.\\(\\)]{2,100}$')])),
                ('generic_name', models.CharField(blank=True, help_text='Generic name of the medicine', max_length=100, null=True)),
                ('category', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('OINTMENT', 'Ointment'), ('DROP', 'Drop'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='TABLET', help_text='Medicine category', max_length=20)),
                ('batch_number', models.CharField(help_text='Batch number', max_length=50, validators=[django.core.validators.RegexValidator(message='Batch number must be 3-50 characters (letters, numbers, hyphens)', regex='^[A-Z0-9\\-]{3,50}$')])),
                ('expiry_date', models.DateField(help_text='Expiry date')),
                ('quantity_in_stock', models.IntegerField(help_text='Quantity currently in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.IntegerField(default=10, help_text='Reorder level alert', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier', models.CharField(blank=True, help_text='Medicine supplier', max_length=100, null=True)),
                ('is_controlled', models.BooleanField(default=False, help_text='Is this a controlled substance?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_restocked', models.DateField(blank=True, help_text='Date when last restocked', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
            ],
            options={
                'verbose_name': 'Medicine Inventory',
                'verbose_name_plural': 'Medicine Inventory',
                'ordering': ['medicine_name', 'expiry_date'],
                'indexes': [models.Index(fields=['medicine_name'], name='pharmacist__medicin_2a442c_idx'), models.Index(fields=['batch_number'], name='pharmacist__batch_n_15fd9f_idx'), models.Index(fields=['expiry_date'], name='pharmacist__expiry__dd8431_idx')],
                'unique_together': {('medicine_name', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='MedicineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.BooleanField(default=False, help_text='Whether medicine has been issued')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date when medicine was issued')),
                ('issue_time', models.TimeField(default=django.utils.timezone.now, help_text='Time when medicine was issued')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('PARTIAL', 'Partially Issued'), ('CANCELLED', 'Cancelled'), ('OUT_OF_STOCK', 'Out of Stock')], default='PENDING', help_text='Current issuance status', max_length=20)),
                ('quantity_issued', models.CharField(blank=True, help_text='Actual quantity issued (e.g., 28 tablets, 100ml)', max_length=50, null=True)),
                ('batch_number', models.CharField(blank=True, help_text='Medicine batch number', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Batch number must be 3-50 characters (letters, numbers, hyphens)', regex='^[A-Z0-9\\-]{3,50}$')])),
                ('expiry_date', models.DateField(blank=True, help_text='Medicine expiry date', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Total price for issued quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('INSURANCE', 'Insurance Covered'), ('WAIVED', 'Waived')], default='PENDING', help_text='Payment status for the medicine', max_length=20)),
                ('instructions_given', models.BooleanField(default=False, help_text='Whether usage instructions were given to patient')),
                ('special_instructions', models.TextField(blank=True, help_text='Additional instructions for the patient', null=True)),
                ('side_effects_explained', models.BooleanField(default=False, help_text='Whether side effects were explained to patient')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_controlled_substance', models.BooleanField(default=False, help_text='Whether this is a controlled substance')),
                ('controlled_substance_log', models.TextField(blank=True, help_text='Log for controlled substance tracking', null=True)),
                ('patient_signature_obtained', models.BooleanField(default=False, help_text='Whether patient signature was obtained (for controlled substances)')),
                ('pharmacist', models.ForeignKey(help_text='Issuing pharmacist', limit_choices_to={'role': 'PHARMACIST'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
                ('prescription', models.ForeignKey(help_text='Select prescription to issue', on_delete=django.db.models.deletion.CASCADE, related_name='medicine_issues', to='doctor.prescription')),
            ],
            options={
                'verbose_name': 'Medicine Issue',
                'verbose_name_plural': 'Medicine Issues',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prescription'], name='pharmacist__prescri_956207_idx'), models.Index(fields=['pharmacist'], name='pharmacist__pharmac_8e7c28_idx'), models.Index(fields=['status'], name='pharmacist__status_136fb0_idx'), models.Index(fields=['issue_date'], name='pharmacist__issue_d_e77384_idx')],
            },
        ),
    ]
