# Generated by Django 5.2.8 on 2025-11-18 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter full name (2-100 characters)', max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters, spaces, apostrophes, hyphens and dots (2-100 characters)', regex="^[a-zA-ZÀ-ÿ\\s\\'\\-\\.]{2,100}$")])),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('DOCTOR', 'Doctor'), ('PHARMACIST', 'Pharmacist'), ('LABTECH', 'Lab Technician')], help_text='Select staff role', max_length=20)),
                ('password', models.CharField(help_text='Hashed password (automatically set when using set_password method)', max_length=128, verbose_name='Password Hash')),
                ('is_active', models.BooleanField(default=True, help_text='Is this staff member active?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date when staff member joined')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login date', null=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['full_name'],
            },
        ),
    ]
