# Generated by Django 5.2.8 on 2025-11-18 08:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='Describe patient symptoms in detail', validators=[django.core.validators.MinLengthValidator(10, message='Symptoms description must be at least 10 characters')])),
                ('diagnosis', models.TextField(help_text='Enter medical diagnosis', validators=[django.core.validators.MinLengthValidator(5, message='Diagnosis must be at least 5 characters')])),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Condition severity level', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional medical notes', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_required', models.BooleanField(default=False, help_text='Does the patient require follow-up?')),
                ('follow_up_date', models.DateField(blank=True, help_text='Suggested follow-up date', null=True)),
                ('is_chronic', models.BooleanField(default=False, help_text='Is this a chronic condition?')),
                ('appointment', models.OneToOneField(help_text='Select appointment for diagnosis', on_delete=django.db.models.deletion.CASCADE, to='receptionist.appointment')),
                ('doctor', models.ForeignKey(help_text='Diagnosing doctor', limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment'], name='doctor_diag_appoint_75abdb_idx'), models.Index(fields=['doctor'], name='doctor_diag_doctor__3ced9e_idx'), models.Index(fields=['severity'], name='doctor_diag_severit_f90593_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Name of the test', max_length=100)),
                ('test_type', models.CharField(choices=[('BLOOD_TEST', 'Blood Test'), ('URINE_TEST', 'Urine Test'), ('IMAGING', 'Imaging'), ('BIOPSY', 'Biopsy'), ('CULTURE', 'Culture'), ('OTHER', 'Other')], default='BLOOD_TEST', help_text='Type of test', max_length=20)),
                ('test_description', models.TextField(blank=True, help_text='Detailed test description and instructions', null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='REQUESTED', help_text='Test status', max_length=20)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT (Immediate)')], default='ROUTINE', help_text='Test priority', max_length=10)),
                ('specimen_type', models.CharField(blank=True, help_text='Type of specimen required (e.g., Blood, Urine, Tissue)', max_length=50, null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Any special instructions for the lab', null=True)),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('is_fasting_required', models.BooleanField(default=False, help_text='Is fasting required for this test?')),
                ('estimated_duration', models.IntegerField(default=60, help_text='Estimated test duration in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('appointment', models.ForeignKey(help_text='Select appointment for lab request', on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='receptionist.appointment')),
                ('doctor', models.ForeignKey(help_text='Requesting doctor', limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
            ],
            options={
                'verbose_name': 'Lab Request',
                'verbose_name_plural': 'Lab Requests',
                'ordering': ['-requested_date'],
                'indexes': [models.Index(fields=['appointment'], name='doctor_labr_appoint_abd363_idx'), models.Index(fields=['doctor'], name='doctor_labr_doctor__1d1214_idx'), models.Index(fields=['status'], name='doctor_labr_status_358443_idx'), models.Index(fields=['priority'], name='doctor_labr_priorit_3f1a5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='Enter medicine name', max_length=100, validators=[django.core.validators.RegexValidator(message='Medicine name can only contain letters, numbers, spaces, hyphens, dots and parentheses', regex='^[a-zA-Z0-9\\s\\-\\.\\(\\)]{2,100}$')])),
                ('dosage', models.CharField(help_text='Enter dosage (e.g., 500mg, 10ml, 1 tablet)', max_length=100, validators=[django.core.validators.RegexValidator(message='Dosage format: 500mg, 10ml, 1 tablet, etc.', regex='^[a-zA-Z0-9\\s\\-\\.\\/]{1,50}$')])),
                ('frequency', models.CharField(choices=[('OD', 'Once Daily'), ('BD', 'Twice Daily'), ('TDS', 'Three Times Daily'), ('QID', 'Four Times Daily'), ('PRN', 'As Required'), ('STAT', 'Immediately')], default='BD', help_text='Medication frequency', max_length=10)),
                ('duration', models.IntegerField(help_text='Treatment duration', validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1'), django.core.validators.MaxValueValidator(365, message='Duration cannot exceed 365')])),
                ('duration_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', help_text='Duration unit', max_length=10)),
                ('quantity', models.CharField(blank=True, help_text='Quantity to dispense (e.g., 30 tablets, 100ml)', max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for medication', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Is this prescription currently active?')),
                ('is_controlled', models.BooleanField(default=False, help_text='Is this a controlled substance?')),
                ('appointment', models.ForeignKey(help_text='Select appointment for prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='receptionist.appointment')),
                ('doctor', models.ForeignKey(help_text='Prescribing doctor', limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment'], name='doctor_pres_appoint_1cb279_idx'), models.Index(fields=['doctor'], name='doctor_pres_doctor__e8840f_idx'), models.Index(fields=['medicine_name'], name='doctor_pres_medicin_d0a97b_idx')],
            },
        ),
    ]
