# Generated by Django 5.2.8 on 2025-11-18 08:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter patient's full name", max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters, spaces, apostrophes, hyphens and dots (2-100 characters)', regex="^[a-zA-ZÀ-ÿ\\s\\'\\-\\.]{2,100}$")])),
                ('age', models.IntegerField(help_text='Patient age', validators=[django.core.validators.MinValueValidator(0, message='Age cannot be negative'), django.core.validators.MaxValueValidator(150, message='Age cannot exceed 150 years')])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text="Select patient's gender", max_length=10)),
                ('address', models.TextField(help_text='Enter complete address', validators=[django.core.validators.MinLengthValidator(10, message='Address must be at least 10 characters long')])),
                ('phone', models.CharField(help_text='Enter phone number', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits, optionally starting with +', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Patient email address (optional)', max_length=254, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits, optionally starting with +', regex='^\\+?1?\\d{9,15}$')])),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Patient blood group', max_length=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medical_history', models.TextField(blank=True, help_text='Any known medical conditions or history', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Any known allergies', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this patient active in the system?')),
                ('created_by', models.ForeignKey(help_text='Receptionist who registered the patient', limit_choices_to={'role': 'RECEPTIONIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.staff')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Select appointment date')),
                ('appointment_time', models.TimeField(help_text='Select appointment time')),
                ('purpose', models.TextField(help_text='Reason for appointment', validators=[django.core.validators.MinLengthValidator(5, message='Please describe appointment purpose')])),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', help_text='Current appointment status', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Appointment priority level', max_length=10)),
                ('symptoms', models.TextField(blank=True, help_text='Initial symptoms described by patient', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the appointment', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_duration', models.IntegerField(default=30, help_text='Estimated duration in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('actual_duration', models.IntegerField(blank=True, help_text='Actual duration in minutes (filled after completion)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('check_in_time', models.DateTimeField(blank=True, help_text='When patient checked in', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, help_text='When patient checked out', null=True)),
                ('created_by', models.ForeignKey(help_text='Receptionist who created the appointment', limit_choices_to={'role': 'RECEPTIONIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to='adminapp.staff')),
                ('doctor', models.ForeignKey(help_text='Select doctor for appointment', limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staff')),
                ('patient', models.ForeignKey(help_text='Select patient for appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='receptionist.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='receptionis_phone_1cd0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='receptionis_name_4e633b_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='receptionis_is_acti_c7f270_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'appointment_time'], name='receptionis_appoint_d3ecf9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='receptionis_status_593714_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'doctor'], name='receptionis_patient_fcd204_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['priority'], name='receptionis_priorit_aaece2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_date', 'appointment_time')},
        ),
    ]
